name: color_system
description: This plugin simplifies hex color handling, making it effortless to customize visual elements in your application with precision and ease.
version: 0.0.5
homepage: 'https://www.github.com/Jesse-Dan/color_system'

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
